### ISSUE TITLE
Relative import path in editor

### ISSUE THREAD

**Issue by wunki** [cotyhamilton/deno-sveltekit#3]
Thanks for creating this demo app! I tried setting up Deno and the only warning I keep getting in my editor is the following:

`Relative import path "$app/environment" not prefixed with / or ./ or ../`

![CleanShot 2024-10-27 at 06 54 17@2x](https://github.com/user-attachments/assets/41c4f82d-e2f3-47a8-ab2c-e10dce7806f5)

_I'm new to the JS eco-system, so unsure how to fix this myself..._

**Comment by cotyhamilton** [comment]
Hey! I would recommend disabling the deno lsp/deno extension

Sveltekit + deno is still being worked on, and probably in the near future the experience will be nicer and more inline with what you’d expect, but in the meantime I’ve found this way to be the smoothest

**Comment by wunki** [comment]
Understood! Will be patient 👍🏽
